version: '3.1'

services:

  db-concesionario:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 33307:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8181:8080
   
      