# Use root/example as user/password credentials

version: '3.1'

services:

  adminer-gesaca:
    image: adminer
    restart: "no"
    ports:
      - 8182:8080

  db-gesaca:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: zx76wbz7FG89k
    ports:
      - 33307:3306

